apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  ports:
    - name: cadvisor
      port: 8080
      targetPort: 80
  selector:
    app: frontend
    color: blue
  type: ClusterIP
---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend
spec:
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: frontend
        tier: frontend
        track: stable
        color: blue
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: cadv
          image: proxdocker.azurecr.io/helloworld:v0.5
          env:
            - name: creator
              value: "k8s app"
          ports:
          - containerPort: 80
          volumeMounts:
            - name: frontend-upload
              mountPath: /srv/upload
      volumes:
        - name: frontend-upload
          persistentVolumeClaim:
            claimName: frontend-upload

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: frontend-upload
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 32Gi
  volumeMode:
