apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  ports:
    - name: cadvisor
      port: 8080
      targetPort: 8080
  selector:
    app: frontend
    tier: frontend
    track: stable
    color: blue
  type: LoadBalancer
---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend
spec:
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
        tier: frontend
        track: stable
        color: blue
    spec:
      containers:
        - name: cadv
          image: google/cadvisor
          ports:
          - containerPort: 8080
