apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  ports:
    - name: cadvisor
      port: 8080
    - name: http
      port: 80
    - name: https
      port: 443
  selector:
    app: frontend
    tier: frontend
    track: stable
    color: blue
  type: LoadBalancer
---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend
spec:
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: frontend
        tier: frontend
        track: stable
        color: blue
    spec:
      containers:
        - name: nginx
          image: nginx:1.7.9
          volumeMounts:
          - name: nginx-ssl
            mountPath: /etc/nginx/ssl
            readOnly: true
          - name: nginx-vhost
            mountPath: /etc/nginx/conf.d
        - name: cadv
          image: google/cadvisor
          ports:
          - containerPort: 8080
      volumes:
        - name: nginx-ssl
          secret:
            secretName: nginx-ssl
        - name: nginx-vhost
          configMap:
            name: frontend-nginx-conf
            items:
            - key: frontend-ssl.conf
              path: frontend.conf