---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: frontend.example.com
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx-public"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "false"
spec:
  tls:
    - hosts:
      - frontend.example.com
      secretName: nginx-ssl
  rules:
    - host: frontend.example.com
      http:
        paths:
          - path: /
            backend:
              serviceName: myapp
              servicePort: 80